AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Style/StringLiterals:
  EnforcedStyle: single_quotes
