name: CI

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: db migrate
        run: bundle exec rake db:migrate
        env:
          RAILS_ENV: test
      - name: Run tests
        run: bundle exec rake
